### ISSUE TITLE
Quick navigation bar

### ISSUE THREAD

**Issue by UghtC** [TwoBeers/boozurk#1]
Hi,
  In Chrome you don't see the menu's tool tips - in Firefox you do see them, but they are a fixed height from the top of the page, even if the menu is on a taller page.

Does the same issue if in fixed position or not.

Using Windows 7 Home Premium / Chrome (v.17) / Firefox (v.10)

**Comment by UghtC** [comment]
Addendum: Seems to be my installation - will track down the fault!

**Comment by ilmaren** [comment]
Hi Tim,
did you found out what was wrong?
If yes, please give us a feedback as it could help someone else.
Thanks

**Comment by UghtC** [comment]
Hi,
   Not found the issue yet - theme works OK on my sandbox installation, 
just not on my site currently.  www.saltpeppervinegar.co.uk
Disabling plugins and seeing what happens.

Tim

**Comment by UghtC** [comment]
Ha!  How fast was that?

Found the issue - if you have Photonic Gallery installed, it messes with 
the popups.
I'll leave it to you to think of a way past it; I'll leave Photonic off 
on my site for now as I can live without it  ;-)

all the best,
Tim
