### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by Vanp** [TwoBeers/boozurk#10]
Sorry to bother you with another issue: The RSS button of the"Follow Me" widget cannot be customized with a Feedburner link, for example. Is there any alternative? Or can I modify code in some way so the RSS button contains this link?

Thanks in advance.

Vanessa

**Comment by ilmaren** [comment]
Hi Vanessa,
Rss point to the standard WP feed.
You can modify the link by editing line 563 of the _widget.php_ file inside _wp-contend\themes\boozurk\lib\_ folder
eg. replace

``` php
                $account = get_bloginfo( 'rss2_url' );
```

with

``` php
                $account = "http://yourFeedLink";
```

But beware, you should manually edit it at every update of the theme (maybe we'll add custom feed link support in future, but I can't tell it for sure now).

Hope it helps

**Comment by Vanp** [comment]
Yes, it worked!

Thank you so much Ilmaren.

**Comment by ilmaren** [comment]
:-)
