### ISSUE TITLE
What happened to "Pages" in Mobile View...?

### ISSUE THREAD

**Issue by 11racine** [TwoBeers/boozurk#11]
Hi, with your last update the "pages" have since dissappeared from the mobile view. Can you tell me how to add this back?? I do need to also show my "pages" on mobile view. Thank you!! :)

**Comment by jimo** [comment]
Pages list in mobile view has been removed. You can add them back by dragging the "Pages" widget or the "Custom Menu" widget to the "Mobile Widget Area"

**Comment by 11racine** [comment]
Ohhhh coool!
