### ISSUE TITLE
Navigation buttons

### ISSUE THREAD

**Issue by Vanp** [TwoBeers/boozurk#13]
Hi again, I had to upload the theme again and I don't remember how can I remove the navigation buttons from the right side (http://www.comunicosmos.com).

Thanks a million.

Vanessa

**Comment by jimo** [comment]
Hi Vanessa

you can either
- delete line 48 on functions.php `add_action( 'boozurk_hook_footer_before'           , 'boozurk_navigation' );`

or
- add the "navigation button" widget to a sidebar (no matter what) and uncheck every button in the widget

hope it helps
Bye

**Comment by Vanp** [comment]
Thanks, I had forgotten the easiest one. I'll go for the second option :-)

Just another question, each time I insert an email address in the appropriate box of the Follow Me widget, an "Invalid value" message displays. Do you know why? I tried with a couple of email addresses unsuccessfully.

**Comment by jimo** [comment]
My fault,sorry. It'll be fixed in next revision.
By now, if you want a super-fast fix, do the following
- open lib/widgets.php
- replace the line 930 `$pattern = "/^(http|https):\/\//";` with `$pattern = "/./";`
- save & close

**Comment by Vanp** [comment]
Thank you, it worked!
