### ISSUE TITLE
Navigations buttons not working....

### ISSUE THREAD

**Issue by 11racine** [TwoBeers/boozurk#15]
Hi, these buttons do nothing when clicked on... how can I fix this?

thank you!! :)

capandleo.com

**Comment by ilmaren** [comment]
Hi racine,
We are on holiday so I can't be so usefull (just a phone in my hands and no tools).
I think it could be a js conflict, so please try disable js animations in appearance - theme options

Hope it helps
Cheers

Inviato da Android.

-----Original Message-----

**Comment by 11racine** [comment]
I went to Theme Options > Javascript, and disabled everything.... still didn't work :/

**Comment by ilmaren** [comment]
Hi racine,
navigation buttons work correctly on your web site, can you confirm?

**Comment by 11racine** [comment]
I had to pay someone to fix them for me.

**Comment by ilmaren** [comment]
Really sorry about that, but, as I wrote you, we were on holiday and was impossible for us give you a better support.

**Comment by 11racine** [comment]
That's fine.. Im sure i'll have other questions at some point soon. Thanks.
