### ISSUE TITLE
Customize core-mobile.php...

### ISSUE THREAD

**Issue by 11racine** [TwoBeers/boozurk#16]
Hello, I am trying to make the "Mobile Widget Area" appear before the "posts" within the mobile view.... Do you have an easy solution for this?

Thank you!

**Comment by jimo** [comment]
Hi, sorry for the long wait ( I missed your request ).

The solution is the following:

Open mobile/footer-mobile.php file and move (line 11)
`<?php locate_template( array( 'mobile/sidebar-mobile.php' ), true, false ); ?>`
to the end of file mobile/header-mobile.php

**Comment by 11racine** [comment]
Great! Thanks so much!

**Comment by jimo** [comment]
you're welcome
