### ISSUE TITLE
Why does the Comment feature not work?

### ISSUE THREAD

**Issue by Blogitudes** [TwoBeers/boozurk#17]
When desktop & smartphone visitors to my blog try to Comment on an article they get an error message that their JavaScript may not be enabled. They have checked their internet settings on their devices and JavaScript IS enabled. Why does my theme not allow their comments to go through? To date, the only way the Comment feature on my blog works is by using an iPad. Please help! I want non-iPad users to be able to comment.

**Comment by jimo** [comment]
Are you using a plugin for comments? Like Spam Free for WordPress? In this case, try to disable it and see what happens. Our theme doesn't use js for comments, so it's likely a plugin issue

**Comment by ilmaren** [comment]
User change the theme.
Closed
