### ISSUE TITLE
Quick Navigation links broken

### ISSUE THREAD

**Issue by feintb70** [TwoBeers/boozurk#18]
I would like to customize which quick nav links are appearing. Nothing happens when I uncheck them in the widget menu.

Nothing happens when I delete line 48 in functions php. 

What can I do?

Thank you!

**Comment by jimo** [comment]
Search for the function `boozurk_navbuttons` inside functions.php file (at line 689 or so).
You can see this piece of code at the beginning

```
        $defaults = array(
            'print'     => 1,
            'comment'   => 1,
            'feed'      => 1,
            'trackback' => 1,
            'home'      => 1,
            'next_prev' => 1,
            'up_down'   => 1,
            'fixed'     => 1,
        );

```

Just set to 0 the unwanted buttons
