### ISSUE TITLE
Categories view gives 404 error

### ISSUE THREAD

**Issue by hiddenrelic** [TwoBeers/boozurk#19]
I have this issue on two subdomains that are using this theme. Most categories come up with the error "Sorry, you're looking for something that isn't here: http://techie.rebeccagregory.us/category/welcome-to-the-internet/" when you try to pull up all posts in that category.

site: techie.rebeccagregory.us
![categories](https://cloud.githubusercontent.com/assets/8572641/4066865/357226aa-2e28-11e4-89ca-c1965c3ec75f.PNG)

site: sixlegsfoundation.rebeccagregory.us
![categories2](https://cloud.githubusercontent.com/assets/8572641/4066889/7f9a02d4-2e28-11e4-9415-f0a397bf2352.PNG)

**Comment by ilmaren** [comment]
Hi,

please try to re-set you permalinks and double check you category name and slug.

Usually these kind of errors are not theme related, anyway try to set one of the default themes and check if the problem persist.

Hope it helps

**Comment by hiddenrelic** [comment]
That fixed it. Thanks.
