### ISSUE TITLE
"Desktop View" on mobile device...

### ISSUE THREAD

**Issue by 11racine** [TwoBeers/boozurk#6]
Hello,

When I access my site from my iPhone or mobile device the theme automatically goes to "mobile view" mode, and that's cool... but my issue is that when I select "desktop view" on my mobile device, the content container with the whole middle section of the site content is squished together... is there any way to fix this? It would be nice to see the site in "desktop view" from a mobile device... 

Please let me know what I can do or what has to be tweaked... Thank you!

capandleo.com

**Comment by jimo** [comment]
Hi, maybe with some css styling but that's not easy. We made a mobile mode just for this purpose. If the theme was mobile compatible, the mobile view would be useless
