### ISSUE TITLE
Assistance required to place author name with posts

### ISSUE THREAD

**Issue by gigamac** [TwoBeers/boozurk#7]
Can the theme settings please include an option to place the author name or author link (preferred) with each post.

This is really causign me stress - I can see the help from regular wordpress support on how to do it, and i can see the burzooka function where the details are processed, but I can't see how to use the function to get what I want, and i don't want to hack!!!

**Comment by ilmaren** [comment]
I can't clearly understand what you want.

BTW if you need to display post details, go to widget and add _Post details_ widget to _Post Widget Area_ (this will add post details, including a link to author page - author page in WP is a page filled with articles from that very author...actually nothing special).

**Comment by gigamac** [comment]
D'uh, how dumb do I feel? Very!

Post widget area just didn't register with me until you pointed it out...

Works fine in post page, thanks!

Bests
Iain

Sent from my iPhone

On 7 Dec 2012, at 07:48, ilmaren notifications@github.com wrote:

I can't clearly understand what you want.

BTW if you need to display post details, go to widget and add _Post
details_widget to
_Post Widget Area_ (this will add post details, including a link to author
page - author page in WP is a page filled with articles from that very
author...actually nothing special).

—
Reply to this email directly or view it on
GitHubhttps://github.com/TwoBeers/boozurk/issues/7#issuecomment-11121681.

**Comment by ilmaren** [comment]
Pleased I help you out :-)

Cheers

**Comment by gigamac** [comment]
Much appreciated!

Sent from my iPhone

On 7 Dec 2012, at 08:41, ilmaren notifications@github.com wrote:

Pleased I help you out :-)

Cheers

—
Reply to this email directly or view it on
GitHubhttps://github.com/TwoBeers/boozurk/issues/7#issuecomment-11122681.
